import { useState } from 'react';
import { doc, serverTimestamp, setDoc } from 'firebase/firestore';
import { User as UserIcon } from 'lucide-react';
import type { Tab, UserProfile } from '../types';
import { db, logout } from '../lib/firebase';
import { uploadUserFile } from '../hooks/useUpload';
import { Input, Select } from './QuickLog';

export function Profile({ profile, setTab }: { profile: UserProfile; setTab: (tab: Tab) => void }) {
  const [draft, setDraft] = useState(profile);
  async function photo(file?: File) { if (!file || !db) return; const up = await uploadUserFile(profile.uid, 'profile', file); setDraft({ ...draft, photoURL: up.url }); await setDoc(doc(db, 'users', profile.uid), { photoURL: up.url, updatedAt: serverTimestamp() }, { merge: true }); }
  async function save() { if (!db) return; await setDoc(doc(db, 'users', profile.uid), { ...draft, updatedAt: serverTimestamp() }, { merge: true }); }
  const cert = draft.certificationProfile || {};
  return <section className="panel p-5"><div className="mb-4 flex items-center gap-3">{draft.photoURL ? <img className="h-16 w-16 rounded-3xl object-cover" src={draft.photoURL} /> : <div className="grid h-16 w-16 place-items-center rounded-3xl bg-cyan-50"><UserIcon /></div>}<div><h1 className="display text-2xl font-black text-sky-900">Profile</h1><p className="text-sm text-slate-600">{draft.email}</p></div></div><input className="input mb-3" type="file" accept="image/*" onChange={(e) => photo(e.target.files?.[0])} /><div className="grid gap-3 sm:grid-cols-2"><Input label="Display name" value={draft.name} onChange={(v) => setDraft({ ...draft, name: v })} /><Input label="Home country" value={draft.homeCountry} onChange={(v) => setDraft({ ...draft, homeCountry: v })} /><Select label="Units" value={draft.units || 'metric'} onChange={(v) => setDraft({ ...draft, units: v as UserProfile['units'] })} options={['metric','imperial']} /><Input label="Agency" value={cert.agency} onChange={(v) => setDraft({ ...draft, certificationProfile: { ...cert, agency: v } })} /><Input label="Level" value={cert.level} onChange={(v) => setDraft({ ...draft, certificationProfile: { ...cert, level: v } })} /><Input label="Certification #" value={cert.certificationNumber} onChange={(v) => setDraft({ ...draft, certificationProfile: { ...cert, certificationNumber: v } })} /><Input label="Issue date" type="date" value={cert.issueDate} onChange={(v) => setDraft({ ...draft, certificationProfile: { ...cert, issueDate: v } })} /><Input label="Instructor" value={cert.instructorName} onChange={(v) => setDraft({ ...draft, certificationProfile: { ...cert, instructorName: v } })} /></div><div className="mt-4 flex flex-wrap gap-2"><button className="btn btn-primary" onClick={save}>Save</button><button className="btn btn-soft" onClick={() => setTab('watch')}>Watch Preview</button><button className="btn btn-soft" onClick={() => setTab('kb')}>Knowledge Base</button><button className="btn btn-soft" onClick={logout}>Logout</button></div></section>;
}

export function Settings({ setTab }: { setTab: (tab: Tab) => void }) {
  const [message, setMessage] = useState('');
  async function api(path: string, body?: unknown) { const res = await fetch(path, { method: body ? 'POST' : 'GET', headers: { 'Content-Type': 'application/json' }, body: body ? JSON.stringify(body) : undefined }); setMessage(await res.text()); }
  return <div className="space-y-4"><h1 className="display text-2xl font-black text-sky-900">Settings</h1><section className="panel p-5"><h2 className="font-black">Admin Tools</h2><div className="mt-3 flex flex-wrap gap-2"><button className="btn btn-primary" onClick={() => setTab('kb')}>Knowledge Base</button><button className="btn btn-soft" onClick={() => api('/api/admin/sync-reference-data', {})}>Sync Reference Data</button><button className="btn btn-soft" onClick={() => api('/api/kb/admin/shared-key/status')}>AI Key Status</button></div>{message && <pre className="mt-3 overflow-auto rounded-2xl bg-slate-100 p-3 text-xs">{message}</pre>}</section><section className="panel p-5"><h2 className="font-black">User Role Management</h2><p className="mt-2 text-sm text-slate-600">Manage roles in backend-managed admins/{'{uid}'} records or extend /api/admin routes.</p></section></div>;
}
