import { useMemo, useState } from 'react';
import { Plus, Trash2 } from 'lucide-react';
import type { DiveSite, Species } from '../types';
import { atolls } from '../lib/reference';
import { saveDoc } from '../hooks/useFirebaseCollection';
import { Input, Select } from './QuickLog';

export function DiveSites({ sites, uid, isAdmin }: { sites: DiveSite[]; uid: string; isAdmin: boolean }) {
  const [q, setQ] = useState(''); const [atoll, setAtoll] = useState(''); const [draft, setDraft] = useState<Partial<DiveSite>>({ difficulty: 'beginner', atoll: 'North Male' });
  const filtered = useMemo(() => sites.filter((s) => (!q || `${s.name} ${s.atoll}`.toLowerCase().includes(q.toLowerCase())) && (!atoll || s.atoll === atoll)), [sites, q, atoll]);
  async function add() { if (!draft.name) return; await saveDoc('diveSites', undefined, { ...draft, id: '', createdBy: uid }); setDraft({ difficulty: 'beginner', atoll: 'North Male' }); }
  return <div className="space-y-4"><h1 className="display text-2xl font-black text-sky-900">Dive Sites</h1><div className="panel grid gap-3 p-4 sm:grid-cols-3"><Input label="Search" value={q} onChange={setQ} /><Select label="Atoll" value={atoll} onChange={setAtoll} options={['', ...atolls]} names={{ '': 'All atolls' }} /><Select label="Quick select" value="" onChange={(id) => setQ(sites.find((s) => s.id === id)?.name || '')} options={['', ...sites.map((s) => s.id)]} names={{ '': 'Choose', ...Object.fromEntries(sites.map((s) => [s.id, s.name])) }} /></div>{!filtered.length && <p className="panel p-5 text-sm text-slate-600">{isAdmin ? 'Sync reference data from Settings to populate dive sites.' : 'No matching dive sites yet.'}</p>}<div className="grid gap-3 md:grid-cols-2">{filtered.map((s) => <Card key={s.id} title={s.name} meta={`${s.atoll} · ${s.type || 'Site'}`} badges={[s.difficulty || '', `${s.depthMin || 0}-${s.depthMax || '?'}m`, s.current || '', s.isProtected ? 'Protected' : '', s.regulatedAccess ? 'Regulated' : '']} body={s.description} />)}</div><section className="panel p-4"><h2 className="display mb-3 text-lg font-black">Custom Site</h2><div className="grid gap-3 sm:grid-cols-2"><Input label="Name" value={draft.name} onChange={(v) => setDraft({ ...draft, name: v })} /><Select label="Atoll" value={draft.atoll || ''} onChange={(v) => setDraft({ ...draft, atoll: v })} options={atolls} /><Input label="Depth min" type="number" value={draft.depthMin} onChange={(v) => setDraft({ ...draft, depthMin: Number(v) })} /><Input label="Depth max" type="number" value={draft.depthMax} onChange={(v) => setDraft({ ...draft, depthMax: Number(v) })} /></div><button className="btn btn-primary mt-3" onClick={add}><Plus size={17} />Add site</button></section></div>;
}

export function SpeciesGuide({ species, uid }: { species: Species[]; uid: string }) {
  const [q, setQ] = useState(''); const [cat, setCat] = useState(''); const [draft, setDraft] = useState<Partial<Species>>({ category: 'Fish', rarity: 'Common' });
  const filtered = species.filter((s) => (!q || `${s.name} ${s.scientificName}`.toLowerCase().includes(q.toLowerCase())) && (!cat || s.category === cat));
  async function add() { if (!draft.name) return; await saveDoc('marineLife', undefined, { ...draft, id: '', createdBy: uid }); setDraft({ category: 'Fish', rarity: 'Common' }); }
  return <div className="space-y-4"><div className="flex items-center justify-between"><h1 className="display text-2xl font-black text-sky-900">Species Guide</h1><span className="badge">0/{species.length} photos</span></div><div className="panel grid gap-3 p-4 sm:grid-cols-3"><Input label="Search" value={q} onChange={setQ} /><Select label="Category" value={cat} onChange={setCat} options={['','Shark','Ray','Fish','Macro','Reptile','Other']} names={{ '': 'All' }} /><Select label="Quick select" value="" onChange={(id) => setQ(species.find((s) => s.id === id)?.name || '')} options={['', ...species.map((s) => s.id)]} names={{ '': 'Choose', ...Object.fromEntries(species.map((s) => [s.id, s.name])) }} /></div><div className="grid gap-3 md:grid-cols-2">{filtered.map((s) => <Card key={s.id} title={s.name} meta={`${s.scientificName || ''} · ${s.category}`} badges={[s.rarity || 'Common', s.imageUrl ? 'Reference photo' : 'No photo']} body={s.description} />)}</div><section className="panel p-4"><h2 className="display mb-3 text-lg font-black">Custom Species</h2><div className="grid gap-3 sm:grid-cols-2"><Input label="Common name" value={draft.name} onChange={(v) => setDraft({ ...draft, name: v })} /><Input label="Scientific name" value={draft.scientificName} onChange={(v) => setDraft({ ...draft, scientificName: v })} /><Select label="Category" value={draft.category || 'Fish'} onChange={(v) => setDraft({ ...draft, category: v as Species['category'] })} options={['Shark','Ray','Fish','Macro','Reptile','Other']} /><Select label="Rarity" value={draft.rarity || 'Common'} onChange={(v) => setDraft({ ...draft, rarity: v as Species['rarity'] })} options={['Common','Uncommon','Rare','Legendary']} /></div><button className="btn btn-primary mt-3" onClick={add}><Plus size={17} />Add species</button></section></div>;
}

function Card({ title, meta, badges, body }: { title: string; meta: string; badges: string[]; body?: string }) {
  const [open, setOpen] = useState(false);
  return <article className="panel p-4"><button className="w-full text-left" onClick={() => setOpen(!open)}><h2 className="font-black text-sky-900">{title}</h2><p className="text-sm text-slate-600">{meta}</p><div className="mt-2 flex flex-wrap gap-2">{badges.filter(Boolean).map((b) => <span className="badge" key={b}>{b}</span>)}</div></button>{open && <div className="mt-3 border-t pt-3 text-sm text-slate-700"><p>{body || 'No description yet.'}</p><button className="btn btn-soft mt-3"><Trash2 size={15} />Delete custom</button></div>}</article>;
}
