import { useMemo, useState } from 'react';
import type { ReactElement } from 'react';
import { LineChart, Line, XAxis, YAxis, Tooltip, ResponsiveContainer, BarChart, Bar } from 'recharts';
import type { DiveLog, TeamDive } from '../types';
import { saveDoc } from '../hooks/useFirebaseCollection';
import { Input } from './QuickLog';

export function TeamDives({ uid, name, dives, logs, onLog }: { uid: string; name: string; dives: TeamDive[]; logs: DiveLog[]; onLog: () => void }) {
  const [mode, setMode] = useState<'upcoming' | 'past'>('upcoming');
  const [draft, setDraft] = useState<Partial<TeamDive>>({ date: new Date().toISOString().slice(0,10), status: 'planned', diveType: 'fun', atoll: 'North Male' });
  const shown = dives.filter((d) => mode === 'past' ? d.status === 'completed' : d.status !== 'completed');
  async function create() { if (!draft.title) return; await saveDoc('teamDives', undefined, { ...draft, id: '', ownerId: uid, ownerName: name, memberIds: [uid], checklist: { briefing: false, gear: false, gas: false }, buddyPairs: [] }); setDraft({ date: new Date().toISOString().slice(0,10), status: 'planned', diveType: 'fun' }); }
  async function copy(d: TeamDive) { await saveDoc('diveLogs', undefined, { id: '', userId: uid, diveNumber: Math.max(0, ...logs.map((l) => l.diveNumber || 0)) + 1, date: d.date, customSiteName: d.customSiteName || d.title, atoll: d.atoll || 'North Male', duration: d.plannedBottomTime || 45, maxDepth: d.plannedMaxDepth || 18, gasType: d.gasType || 'air', oxygenPercent: d.oxygenPercent || 21, tankSize: 12, entryType: 'boat', safetyStop: true, teamDiveId: d.id, teamDiveTitle: d.title, teamDiveRole: 'member', syncStatus: 'synced' }); onLog(); }
  return <div className="space-y-4"><h1 className="display text-2xl font-black text-sky-900">Maruhabaa, Team Dives</h1><div className="panel flex gap-2 p-2">{['upcoming','past'].map((m) => <button key={m} onClick={() => setMode(m as typeof mode)} className={`btn flex-1 ${mode === m ? 'btn-primary' : 'btn-soft'}`}>{m}</button>)}</div><section className="panel p-4"><h2 className="display mb-3 text-lg font-black">Create Dive</h2><div className="grid gap-3 sm:grid-cols-2"><Input label="Title" value={draft.title} onChange={(v) => setDraft({ ...draft, title: v })} /><Input label="Date" type="date" value={draft.date} onChange={(v) => setDraft({ ...draft, date: v })} /><Input label="Depth" type="number" value={draft.plannedMaxDepth} onChange={(v) => setDraft({ ...draft, plannedMaxDepth: Number(v) })} /><Input label="Bottom time" type="number" value={draft.plannedBottomTime} onChange={(v) => setDraft({ ...draft, plannedBottomTime: Number(v) })} /></div><button className="btn btn-primary mt-3" onClick={create}>Create</button></section><div className="grid gap-3">{shown.map((d) => <article className="panel p-4" key={d.id}><div className="flex justify-between gap-3"><div><h2 className="font-black text-sky-900">{d.title}</h2><p className="text-sm text-slate-600">{d.date} · {d.status} · {d.plannedMaxDepth || '-'}m</p></div><span className="badge">{d.memberIds?.length || 1} team</span></div><div className="mt-3 grid gap-2 text-sm sm:grid-cols-2"><p>Checklist: {Object.entries(d.checklist || {}).map(([k,v]) => `${k}:${v ? 'yes' : 'no'}`).join(' · ') || '-'}</p><p>Buddy pairs: {(d.buddyPairs || []).join(', ') || '-'}</p></div><div className="mt-3 flex flex-wrap gap-2"><button className="btn btn-soft" onClick={() => saveDoc('teamDives', d.id, { status: 'completed' })}>Complete</button><button className="btn btn-primary" onClick={() => copy(d)}>Copy to My Logbook</button></div></article>)}</div></div>;
}

export function Insights({ logs }: { logs: DiveLog[] }) {
  const totalTime = logs.reduce((a, l) => a + Number(l.duration || 0), 0);
  const depth = [{ name: '0-10', value: logs.filter((l) => l.maxDepth <= 10).length }, { name: '10-20', value: logs.filter((l) => l.maxDepth > 10 && l.maxDepth <= 20).length }, { name: '20+', value: logs.filter((l) => l.maxDepth > 20).length }];
  const sac = logs.filter((l) => l.sac).slice(0, 10).reverse().map((l) => ({ dive: `#${l.diveNumber}`, sac: l.sac }));
  const sightings = useMemo(() => Object.entries(logs.flatMap((l) => l.marineLife || []).reduce<Record<string, number>>((a, s) => ({ ...a, [s]: (a[s] || 0) + 1 }), {})).sort((a,b) => b[1] - a[1]).slice(0,5), [logs]);
  const deepest = logs.reduce((a, l) => l.maxDepth > (a?.maxDepth || 0) ? l : a, logs[0]);
  const longest = logs.reduce((a, l) => l.duration > (a?.duration || 0) ? l : a, logs[0]);
  return <div className="space-y-4"><h1 className="display text-2xl font-black text-sky-900">Insights</h1><div className="grid gap-3 sm:grid-cols-4"><Stat label="Bottom time" value={`${totalTime}m`} /><Stat label="Dives" value={logs.length} /><Stat label="Deepest" value={`${deepest?.maxDepth || 0}m`} /><Stat label="Longest" value={`${longest?.duration || 0}m`} /></div><Chart title="Depth Distribution"><BarChart data={depth}><XAxis dataKey="name" /><YAxis allowDecimals={false} /><Tooltip /><Bar dataKey="value" fill="#0891b2" radius={8} /></BarChart></Chart><Chart title="SAC Trend"><LineChart data={sac}><XAxis dataKey="dive" /><YAxis /><Tooltip /><Line type="monotone" dataKey="sac" stroke="#075985" strokeWidth={3} /></LineChart></Chart><section className="panel p-4"><h2 className="display mb-3 text-lg font-black">Top Sightings</h2>{sightings.map(([name, n]) => <p className="flex justify-between border-b py-2 text-sm" key={name}><span>{name}</span><b>{n}</b></p>)}</section></div>;
}
function Chart({ title, children }: { title: string; children: ReactElement }) { return <section className="panel h-72 p-4"><h2 className="display mb-3 text-lg font-black">{title}</h2><ResponsiveContainer width="100%" height="82%">{children}</ResponsiveContainer></section>; }
function Stat({ label, value }: { label: string; value: string | number }) { return <div className="panel p-4"><p className="text-xs font-black uppercase text-slate-500">{label}</p><p className="mono text-2xl font-black text-sky-900">{value}</p></div>; }
